# vim:syntax=yaml
version: 2
jobs:
  build_fedora:
    docker:
      - image: fedora:40
    steps:
      - checkout:
      - run:
          name: Install dependencies
          command: |
            dnf install -y --nodocs 'dnf-command(copr)' && \
            dnf -y copr enable thofmann/clips-6.31 && \
            dnf -y copr enable tavie/clips_protobuf && \
            dnf -y copr enable tavie/paho-mqtt-cpp && \
            dnf -y copr enable tavie/mongo-cxx-driver && \
            dnf install -y --nodocs \
              utf8proc-devel \
              libbson-devel \
              apr-util-devel \
              avahi-devel \
              boost-devel \
              clang \
              clang-tools-extra \
              clips-devel \
              clipsmm-devel \
              diffutils \
              findutils \
              freeopcua-devel \
              gcc-c++ \
              gecode-devel \
              git \
              glibmm24-devel \
              gtkmm30-devel \
              libmicrohttpd-devel \
              make \
              mongo-cxx-driver-devel \
              ncurses-devel \
              openssh-clients \
              openssl-devel \
              protobuf-compiler \
              protobuf-devel \
              protobuf_comm-devel \
              rapidjson-devel \
              which \
              yaml-cpp-devel \
              yamllint \
              cmake \
              paho-c-devel \
              paho-mqtt-cpp \
              python3-pip \
              mongo-c-driver-devel \
              paho-mqtt-cpp-devel && \
              pip3 install pre-commit && \
              git submodule update --init --recursive
      - run:
          name: Install Pre-Commit Hooks
          command: pre-commit install
      - run:
          name: Run Pre-Commit Checks
          command: pre-commit run --all-files
      - run:
          name: Configure CMake
          command: mkdir -p build && cd build && cmake ..
      - run:
          name: Build All Targets
          command: cd build && cmake --build .
workflows:
  version: 2
  build:
    jobs:
      - build_fedora
